spring.application.name=api-gateway
# C'est la porte d'entrée, on lui donne souvent le port 8080 ou 8888
server.port=8180

# S'enregistrer auprès de Eureka 
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ======= ROUTAGE (Où envoyer chaque requête !) =======

# 1. Route pour "Evenementiel" (votre module)
spring.cloud.gateway.routes[0].id=EVENEMENTIEL
# "lb://" signifie "Load Balancer" => trouve l'IP via Eureka grâce au nom "evenementiel-ms"
spring.cloud.gateway.routes[0].uri=lb://evenementiel-ms
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/events/**

# 2. Route pour "Cours" (le module de votre collègue)
spring.cloud.gateway.routes[1].id=COURS
spring.cloud.gateway.routes[1].uri=lb://cours-ms
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/cours/**

# ======= SECURITE (KEYCLOAK) =======
# L'URL de votre Realm Keycloak (A modifier si votre port ou nom de realm diffèrent)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/e-learn
