#server.port=8085
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.register-with-eureka=true
#
#spring.cloud.gateway.server.webmvc.routes[0].id=cours-service
#spring.cloud.gateway.server.webmvc.routes[0].uri=lb://cours
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/cours,/api/cours/**
#
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.reactor.netty.http.client=DEBUG
welcome.message=Welcome to the API Gateway!
