import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'courses' },
  { path: 'frontoffice', pathMatch: 'full', redirectTo: 'courses' },
  { path: 'admin', pathMatch: 'full', redirectTo: 'courses' },
  { path: 'admin/index', pathMatch: 'full', redirectTo: 'courses' },
  { path: 'courses', loadChildren: () => import('./courses/courses.module').then(m => m.CoursesModule) },
  { path: 'frontoffice/about-us', loadComponent: () => import('./frontoffice-pages/about-us/about-us.component').then((m) => m.AboutUsFrontofficePageComponent) },
  { path: 'frontoffice/add-course', loadComponent: () => import('./frontoffice-pages/add-course/add-course.component').then((m) => m.AddCourseFrontofficePageComponent) },
  { path: 'frontoffice/become-an-instructor', loadComponent: () => import('./frontoffice-pages/become-an-instructor/become-an-instructor.component').then((m) => m.BecomeAnInstructorFrontofficePageComponent) },
  { path: 'frontoffice/blog-2-grid', loadComponent: () => import('./frontoffice-pages/blog-2-grid/blog-2-grid.component').then((m) => m.Blog2GridFrontofficePageComponent) },
  { path: 'frontoffice/blog-3-grid', loadComponent: () => import('./frontoffice-pages/blog-3-grid/blog-3-grid.component').then((m) => m.Blog3GridFrontofficePageComponent) },
  { path: 'frontoffice/blog-carousal', loadComponent: () => import('./frontoffice-pages/blog-carousal/blog-carousal.component').then((m) => m.BlogCarousalFrontofficePageComponent) },
  { path: 'frontoffice/blog-details', loadComponent: () => import('./frontoffice-pages/blog-details/blog-details.component').then((m) => m.BlogDetailsFrontofficePageComponent) },
  { path: 'frontoffice/blog-details-left-sidebar', loadComponent: () => import('./frontoffice-pages/blog-details-left-sidebar/blog-details-left-sidebar.component').then((m) => m.BlogDetailsLeftSidebarFrontofficePageComponent) },
  { path: 'frontoffice/blog-details-right-sidebar', loadComponent: () => import('./frontoffice-pages/blog-details-right-sidebar/blog-details-right-sidebar.component').then((m) => m.BlogDetailsRightSidebarFrontofficePageComponent) },
  { path: 'frontoffice/blog-grid', loadComponent: () => import('./frontoffice-pages/blog-grid/blog-grid.component').then((m) => m.BlogGridFrontofficePageComponent) },
  { path: 'frontoffice/blog-left-sidebar', loadComponent: () => import('./frontoffice-pages/blog-left-sidebar/blog-left-sidebar.component').then((m) => m.BlogLeftSidebarFrontofficePageComponent) },
  { path: 'frontoffice/blog-masonry', loadComponent: () => import('./frontoffice-pages/blog-masonry/blog-masonry.component').then((m) => m.BlogMasonryFrontofficePageComponent) },
  { path: 'frontoffice/blog-right-sidebar', loadComponent: () => import('./frontoffice-pages/blog-right-sidebar/blog-right-sidebar.component').then((m) => m.BlogRightSidebarFrontofficePageComponent) },
  { path: 'frontoffice/cart', loadComponent: () => import('./frontoffice-pages/cart/cart.component').then((m) => m.CartFrontofficePageComponent) },
  { path: 'frontoffice/checkout', loadComponent: () => import('./frontoffice-pages/checkout/checkout.component').then((m) => m.CheckoutFrontofficePageComponent) },
  { path: 'frontoffice/coming-soon', loadComponent: () => import('./frontoffice-pages/coming-soon/coming-soon.component').then((m) => m.ComingSoonFrontofficePageComponent) },
  { path: 'frontoffice/contact-us', loadComponent: () => import('./frontoffice-pages/contact-us/contact-us.component').then((m) => m.ContactUsFrontofficePageComponent) },
  { path: 'frontoffice/cours', loadComponent: () => import('./frontoffice-2-pages/course/course.component').then((m) => m.CourseFrontoffice2PageComponent) },
  { path: 'frontoffice/course', loadComponent: () => import('./frontoffice-2-pages/course/course.component').then((m) => m.CourseFrontoffice2PageComponent) },
  { path: 'frontoffice/events', loadComponent: () => import('./frontoffice-pages/event-showcase/event-showcase.component').then((m) => m.EventShowcaseFrontofficePageComponent) },
  { path: 'frontoffice/events.html', pathMatch: 'full', redirectTo: 'frontoffice/events' },
  { path: 'frontoffice/course-category', loadComponent: () => import('./frontoffice-pages/course-category/course-category.component').then((m) => m.CourseCategoryFrontofficePageComponent) },
  { path: 'frontoffice/course-category-2', loadComponent: () => import('./frontoffice-pages/course-category-2/course-category-2.component').then((m) => m.CourseCategory2FrontofficePageComponent) },
  { path: 'frontoffice/course-category-3', loadComponent: () => import('./frontoffice-pages/course-category-3/course-category-3.component').then((m) => m.CourseCategory3FrontofficePageComponent) },
  { path: 'frontoffice/course-details', loadComponent: () => import('./frontoffice-pages/course-details/course-details.component').then((m) => m.CourseDetailsFrontofficePageComponent) },
  { path: 'frontoffice/course-details-2', loadComponent: () => import('./frontoffice-pages/course-details-2/course-details-2.component').then((m) => m.CourseDetails2FrontofficePageComponent) },
  { path: 'frontoffice/course-grid', loadComponent: () => import('./frontoffice-pages/course-grid/course-grid.component').then((m) => m.CourseGridFrontofficePageComponent) },
  { path: 'frontoffice/course-list', loadComponent: () => import('./frontoffice-pages/course-list/course-list.component').then((m) => m.CourseListFrontofficePageComponent) },
  { path: 'frontoffice/course-resume', loadComponent: () => import('./frontoffice-pages/course-resume/course-resume.component').then((m) => m.CourseResumeFrontofficePageComponent) },
  { path: 'frontoffice/course-watch', loadComponent: () => import('./frontoffice-pages/course-watch/course-watch.component').then((m) => m.CourseWatchFrontofficePageComponent) },
  { path: 'frontoffice/cours.html', pathMatch: 'full', redirectTo: 'frontoffice/cours' },
  { path: 'frontoffice/course.html', pathMatch: 'full', redirectTo: 'frontoffice/course' },
  { path: 'frontoffice/error-404', loadComponent: () => import('./frontoffice-pages/error-404/error-404.component').then((m) => m.Error404FrontofficePageComponent) },
  { path: 'frontoffice/error-500', loadComponent: () => import('./frontoffice-pages/error-500/error-500.component').then((m) => m.Error500FrontofficePageComponent) },
  { path: 'frontoffice/faq', loadComponent: () => import('./frontoffice-pages/faq/faq.component').then((m) => m.FaqFrontofficePageComponent) },
  { path: 'frontoffice/forgot-password', loadComponent: () => import('./frontoffice-pages/forgot-password/forgot-password.component').then((m) => m.ForgotPasswordFrontofficePageComponent) },
  { path: 'frontoffice/index', loadComponent: () => import('./frontoffice-pages/index/index.component').then((m) => m.IndexFrontofficePageComponent) },
  { path: 'frontoffice/index-2', loadComponent: () => import('./frontoffice-pages/index-2/index-2.component').then((m) => m.Index2FrontofficePageComponent) },
  { path: 'frontoffice/index-3', loadComponent: () => import('./frontoffice-pages/index-3/index-3.component').then((m) => m.Index3FrontofficePageComponent) },
  { path: 'frontoffice/index-4', loadComponent: () => import('./frontoffice-pages/index-4/index-4.component').then((m) => m.Index4FrontofficePageComponent) },
  { path: 'frontoffice/index-5', loadComponent: () => import('./frontoffice-pages/index-5/index-5.component').then((m) => m.Index5FrontofficePageComponent) },
  { path: 'frontoffice/index-6', loadComponent: () => import('./frontoffice-pages/index-6/index-6.component').then((m) => m.Index6FrontofficePageComponent) },
  { path: 'frontoffice/index-rtl', loadComponent: () => import('./frontoffice-pages/index-rtl/index-rtl.component').then((m) => m.IndexRtlFrontofficePageComponent) },
  { path: 'frontoffice/instructor-announcements', loadComponent: () => import('./frontoffice-pages/instructor-announcements/instructor-announcements.component').then((m) => m.InstructorAnnouncementsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-assignment', loadComponent: () => import('./frontoffice-pages/instructor-assignment/instructor-assignment.component').then((m) => m.InstructorAssignmentFrontofficePageComponent) },
  { path: 'frontoffice/instructor-certificate', loadComponent: () => import('./frontoffice-pages/instructor-certificate/instructor-certificate.component').then((m) => m.InstructorCertificateFrontofficePageComponent) },
  { path: 'frontoffice/instructor-course', loadComponent: () => import('./frontoffice-pages/instructor-course/instructor-course.component').then((m) => m.InstructorCourseFrontofficePageComponent) },
  { path: 'frontoffice/instructor-course-grid', loadComponent: () => import('./frontoffice-pages/instructor-course-grid/instructor-course-grid.component').then((m) => m.InstructorCourseGridFrontofficePageComponent) },
  { path: 'frontoffice/instructor-dashboard', loadComponent: () => import('./frontoffice-pages/instructor-dashboard/instructor-dashboard.component').then((m) => m.InstructorDashboardFrontofficePageComponent) },
  { path: 'frontoffice/instructor-details', loadComponent: () => import('./frontoffice-pages/instructor-details/instructor-details.component').then((m) => m.InstructorDetailsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-earnings', loadComponent: () => import('./frontoffice-pages/instructor-earnings/instructor-earnings.component').then((m) => m.InstructorEarningsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-grid', loadComponent: () => import('./frontoffice-pages/instructor-grid/instructor-grid.component').then((m) => m.InstructorGridFrontofficePageComponent) },
  { path: 'frontoffice/instructor-integrations', loadComponent: () => import('./frontoffice-pages/instructor-integrations/instructor-integrations.component').then((m) => m.InstructorIntegrationsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-list', loadComponent: () => import('./frontoffice-pages/instructor-list/instructor-list.component').then((m) => m.InstructorListFrontofficePageComponent) },
  { path: 'frontoffice/instructor-message', loadComponent: () => import('./frontoffice-pages/instructor-message/instructor-message.component').then((m) => m.InstructorMessageFrontofficePageComponent) },
  { path: 'frontoffice/instructor-notifications', loadComponent: () => import('./frontoffice-pages/instructor-notifications/instructor-notifications.component').then((m) => m.InstructorNotificationsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-payout', loadComponent: () => import('./frontoffice-pages/instructor-payout/instructor-payout.component').then((m) => m.InstructorPayoutFrontofficePageComponent) },
  { path: 'frontoffice/instructor-profile', loadComponent: () => import('./frontoffice-pages/instructor-profile/instructor-profile.component').then((m) => m.InstructorProfileFrontofficePageComponent) },
  { path: 'frontoffice/instructor-quiz', loadComponent: () => import('./frontoffice-pages/instructor-quiz/instructor-quiz.component').then((m) => m.InstructorQuizFrontofficePageComponent) },
  { path: 'frontoffice/instructor-quiz-questions', loadComponent: () => import('./frontoffice-pages/instructor-quiz-questions/instructor-quiz-questions.component').then((m) => m.InstructorQuizQuestionsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-quiz-results', loadComponent: () => import('./frontoffice-pages/instructor-quiz-results/instructor-quiz-results.component').then((m) => m.InstructorQuizResultsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-settings', loadComponent: () => import('./frontoffice-pages/instructor-settings/instructor-settings.component').then((m) => m.InstructorSettingsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-statements', loadComponent: () => import('./frontoffice-pages/instructor-statements/instructor-statements.component').then((m) => m.InstructorStatementsFrontofficePageComponent) },
  { path: 'frontoffice/instructor-tickets', loadComponent: () => import('./frontoffice-pages/instructor-tickets/instructor-tickets.component').then((m) => m.InstructorTicketsFrontofficePageComponent) },
  { path: 'frontoffice/lock-screen', loadComponent: () => import('./frontoffice-pages/lock-screen/lock-screen.component').then((m) => m.LockScreenFrontofficePageComponent) },
  { path: 'frontoffice/login', loadComponent: () => import('./frontoffice-pages/login/login.component').then((m) => m.LoginFrontofficePageComponent) },
  { path: 'frontoffice/notifications', loadComponent: () => import('./frontoffice-pages/notifications/notifications.component').then((m) => m.NotificationsFrontofficePageComponent) },
  { path: 'frontoffice/otp', loadComponent: () => import('./frontoffice-pages/otp/otp.component').then((m) => m.OtpFrontofficePageComponent) },
  { path: 'frontoffice/pricing-plan', loadComponent: () => import('./frontoffice-pages/pricing-plan/pricing-plan.component').then((m) => m.PricingPlanFrontofficePageComponent) },
  { path: 'frontoffice/privacy-policy', loadComponent: () => import('./frontoffice-pages/privacy-policy/privacy-policy.component').then((m) => m.PrivacyPolicyFrontofficePageComponent) },
  { path: 'frontoffice/register', loadComponent: () => import('./frontoffice-pages/register/register.component').then((m) => m.RegisterFrontofficePageComponent) },
  { path: 'frontoffice/reset-password', loadComponent: () => import('./frontoffice-pages/reset-password/reset-password.component').then((m) => m.ResetPasswordFrontofficePageComponent) },
  { path: 'frontoffice/set-password', loadComponent: () => import('./frontoffice-pages/set-password/set-password.component').then((m) => m.SetPasswordFrontofficePageComponent) },
  { path: 'frontoffice/student-billing-address', loadComponent: () => import('./frontoffice-pages/student-billing-address/student-billing-address.component').then((m) => m.StudentBillingAddressFrontofficePageComponent) },
  { path: 'frontoffice/student-certificates', loadComponent: () => import('./frontoffice-pages/student-certificates/student-certificates.component').then((m) => m.StudentCertificatesFrontofficePageComponent) },
  { path: 'frontoffice/student-change-password', loadComponent: () => import('./frontoffice-pages/student-change-password/student-change-password.component').then((m) => m.StudentChangePasswordFrontofficePageComponent) },
  { path: 'frontoffice/student-courses', loadComponent: () => import('./frontoffice-pages/student-courses/student-courses.component').then((m) => m.StudentCoursesFrontofficePageComponent) },
  { path: 'frontoffice/student-dashboard', loadComponent: () => import('./frontoffice-pages/student-dashboard/student-dashboard.component').then((m) => m.StudentDashboardFrontofficePageComponent) },
  { path: 'frontoffice/student-details', loadComponent: () => import('./frontoffice-pages/student-details/student-details.component').then((m) => m.StudentDetailsFrontofficePageComponent) },
  { path: 'frontoffice/student-list', loadComponent: () => import('./frontoffice-pages/student-list/student-list.component').then((m) => m.StudentListFrontofficePageComponent) },
  { path: 'frontoffice/student-messages', loadComponent: () => import('./frontoffice-pages/student-messages/student-messages.component').then((m) => m.StudentMessagesFrontofficePageComponent) },
  { path: 'frontoffice/student-notifications', loadComponent: () => import('./frontoffice-pages/student-notifications/student-notifications.component').then((m) => m.StudentNotificationsFrontofficePageComponent) },
  { path: 'frontoffice/student-order-history', loadComponent: () => import('./frontoffice-pages/student-order-history/student-order-history.component').then((m) => m.StudentOrderHistoryFrontofficePageComponent) },
  { path: 'frontoffice/student-profile', loadComponent: () => import('./frontoffice-pages/student-profile/student-profile.component').then((m) => m.StudentProfileFrontofficePageComponent) },
  { path: 'frontoffice/student-quiz', loadComponent: () => import('./frontoffice-pages/student-quiz/student-quiz.component').then((m) => m.StudentQuizFrontofficePageComponent) },
  { path: 'frontoffice/student-quiz-questions', loadComponent: () => import('./frontoffice-pages/student-quiz-questions/student-quiz-questions.component').then((m) => m.StudentQuizQuestionsFrontofficePageComponent) },
  { path: 'frontoffice/student-referral', loadComponent: () => import('./frontoffice-pages/student-referral/student-referral.component').then((m) => m.StudentReferralFrontofficePageComponent) },
  { path: 'frontoffice/student-reviews', loadComponent: () => import('./frontoffice-pages/student-reviews/student-reviews.component').then((m) => m.StudentReviewsFrontofficePageComponent) },
  { path: 'frontoffice/student-settings', loadComponent: () => import('./frontoffice-pages/student-settings/student-settings.component').then((m) => m.StudentSettingsFrontofficePageComponent) },
  { path: 'frontoffice/student-social-profile', loadComponent: () => import('./frontoffice-pages/student-social-profile/student-social-profile.component').then((m) => m.StudentSocialProfileFrontofficePageComponent) },
  { path: 'frontoffice/student-tickets', loadComponent: () => import('./frontoffice-pages/student-tickets/student-tickets.component').then((m) => m.StudentTicketsFrontofficePageComponent) },
  { path: 'frontoffice/student-wishlist', loadComponent: () => import('./frontoffice-pages/student-wishlist/student-wishlist.component').then((m) => m.StudentWishlistFrontofficePageComponent) },
  { path: 'frontoffice/students', loadComponent: () => import('./frontoffice-pages/students/students.component').then((m) => m.StudentsFrontofficePageComponent) },
  { path: 'frontoffice/terms-and-conditions', loadComponent: () => import('./frontoffice-pages/terms-and-conditions/terms-and-conditions.component').then((m) => m.TermsAndConditionsFrontofficePageComponent) },
  { path: 'frontoffice/testimonials', loadComponent: () => import('./frontoffice-pages/testimonials/testimonials.component').then((m) => m.TestimonialsFrontofficePageComponent) },
  { path: 'frontoffice/under-construction', loadComponent: () => import('./frontoffice-pages/under-construction/under-construction.component').then((m) => m.UnderConstructionFrontofficePageComponent) },
  { path: 'admin/about-courses', loadComponent: () => import('./pages/about-courses/about-courses.component').then((m) => m.AboutCoursesPageComponent) },
  { path: 'admin/about-student', loadComponent: () => import('./pages/about-student/about-student.component').then((m) => m.AboutStudentPageComponent) },
  { path: 'admin/add-blog', loadComponent: () => import('./pages/add-blog/add-blog.component').then((m) => m.AddBlogPageComponent) },
  { path: 'admin/add-courses', loadComponent: () => import('./pages/add-courses/add-courses.component').then((m) => m.AddCoursesPageComponent) },
  { path: 'admin/add-departments', loadComponent: () => import('./pages/add-departments/add-departments.component').then((m) => m.AddDepartmentsPageComponent) },
  { path: 'admin/add-email', loadComponent: () => import('./pages/add-email/add-email.component').then((m) => m.AddEmailPageComponent) },
  { path: 'admin/add-fees', loadComponent: () => import('./pages/add-fees/add-fees.component').then((m) => m.AddFeesPageComponent) },
  { path: 'admin/add-holiday', loadComponent: () => import('./pages/add-holiday/add-holiday.component').then((m) => m.AddHolidayPageComponent) },
  { path: 'admin/add-library', loadComponent: () => import('./pages/add-library/add-library.component').then((m) => m.AddLibraryPageComponent) },
  { path: 'admin/add-professor', loadComponent: () => import('./pages/add-professor/add-professor.component').then((m) => m.AddProfessorPageComponent) },
  { path: 'admin/add-staff', loadComponent: () => import('./pages/add-staff/add-staff.component').then((m) => m.AddStaffPageComponent) },
  { path: 'admin/add-student', loadComponent: () => import('./pages/add-student/add-student.component').then((m) => m.AddStudentPageComponent) },
  { path: 'admin/all-courses', loadComponent: () => import('./pages/all-courses/all-courses.component').then((m) => m.AllCoursesPageComponent) },
  { path: 'admin/all-departments', loadComponent: () => import('./pages/all-departments/all-departments.component').then((m) => m.AllDepartmentsPageComponent) },
  { path: 'admin/all-holiday', loadComponent: () => import('./pages/all-holiday/all-holiday.component').then((m) => m.AllHolidayPageComponent) },
  { path: 'admin/all-library', loadComponent: () => import('./pages/all-library/all-library.component').then((m) => m.AllLibraryPageComponent) },
  { path: 'admin/all-professors', loadComponent: () => import('./pages/all-professors/all-professors.component').then((m) => m.AllProfessorsPageComponent) },
  { path: 'admin/all-staff', loadComponent: () => import('./pages/all-staff/all-staff.component').then((m) => m.AllStaffPageComponent) },
  { path: 'admin/all-students', loadComponent: () => import('./pages/all-students/all-students.component').then((m) => m.AllStudentsPageComponent) },
  { path: 'admin/app-calender', loadComponent: () => import('./pages/app-calender/app-calender.component').then((m) => m.AppCalenderPageComponent) },
  { path: 'admin/app-profile', loadComponent: () => import('./pages/app-profile/app-profile.component').then((m) => m.AppProfilePageComponent) },
  { path: 'admin/blog', loadComponent: () => import('./pages/blog/blog.component').then((m) => m.BlogPageComponent) },
  { path: 'admin/blog-category', loadComponent: () => import('./pages/blog-category/blog-category.component').then((m) => m.BlogCategoryPageComponent) },
  { path: 'admin/chart-chartist', loadComponent: () => import('./pages/chart-chartist/chart-chartist.component').then((m) => m.ChartChartistPageComponent) },
  { path: 'admin/chart-chartjs', loadComponent: () => import('./pages/chart-chartjs/chart-chartjs.component').then((m) => m.ChartChartjsPageComponent) },
  { path: 'admin/chart-flot', loadComponent: () => import('./pages/chart-flot/chart-flot.component').then((m) => m.ChartFlotPageComponent) },
  { path: 'admin/chart-morris', loadComponent: () => import('./pages/chart-morris/chart-morris.component').then((m) => m.ChartMorrisPageComponent) },
  { path: 'admin/chart-peity', loadComponent: () => import('./pages/chart-peity/chart-peity.component').then((m) => m.ChartPeityPageComponent) },
  { path: 'admin/chart-sparkline', loadComponent: () => import('./pages/chart-sparkline/chart-sparkline.component').then((m) => m.ChartSparklinePageComponent) },
  { path: 'admin/content', loadComponent: () => import('./pages/content/content.component').then((m) => m.ContentPageComponent) },
  { path: 'admin/content-add', loadComponent: () => import('./pages/content-add/content-add.component').then((m) => m.ContentAddPageComponent) },
  { path: 'admin/ecom-checkout', loadComponent: () => import('./pages/ecom-checkout/ecom-checkout.component').then((m) => m.EcomCheckoutPageComponent) },
  { path: 'admin/ecom-customers', loadComponent: () => import('./pages/ecom-customers/ecom-customers.component').then((m) => m.EcomCustomersPageComponent) },
  { path: 'admin/ecom-invoice', loadComponent: () => import('./pages/ecom-invoice/ecom-invoice.component').then((m) => m.EcomInvoicePageComponent) },
  { path: 'admin/ecom-product-detail', loadComponent: () => import('./pages/ecom-product-detail/ecom-product-detail.component').then((m) => m.EcomProductDetailPageComponent) },
  { path: 'admin/ecom-product-grid', loadComponent: () => import('./pages/ecom-product-grid/ecom-product-grid.component').then((m) => m.EcomProductGridPageComponent) },
  { path: 'admin/ecom-product-list', loadComponent: () => import('./pages/ecom-product-list/ecom-product-list.component').then((m) => m.EcomProductListPageComponent) },
  { path: 'admin/ecom-product-order', loadComponent: () => import('./pages/ecom-product-order/ecom-product-order.component').then((m) => m.EcomProductOrderPageComponent) },
  { path: 'admin/edit-courses', loadComponent: () => import('./pages/edit-courses/edit-courses.component').then((m) => m.EditCoursesPageComponent) },
  { path: 'admin/edit-departments', loadComponent: () => import('./pages/edit-departments/edit-departments.component').then((m) => m.EditDepartmentsPageComponent) },
  { path: 'admin/edit-holiday', loadComponent: () => import('./pages/edit-holiday/edit-holiday.component').then((m) => m.EditHolidayPageComponent) },
  { path: 'admin/edit-library', loadComponent: () => import('./pages/edit-library/edit-library.component').then((m) => m.EditLibraryPageComponent) },
  { path: 'admin/edit-professor', loadComponent: () => import('./pages/edit-professor/edit-professor.component').then((m) => m.EditProfessorPageComponent) },
  { path: 'admin/edit-profile', loadComponent: () => import('./pages/edit-profile/edit-profile.component').then((m) => m.EditProfilePageComponent) },
  { path: 'admin/edit-staff', loadComponent: () => import('./pages/edit-staff/edit-staff.component').then((m) => m.EditStaffPageComponent) },
  { path: 'admin/edit-student', loadComponent: () => import('./pages/edit-student/edit-student.component').then((m) => m.EditStudentPageComponent) },
  { path: 'admin/email-compose', loadComponent: () => import('./pages/email-compose/email-compose.component').then((m) => m.EmailComposePageComponent) },
  { path: 'admin/email-inbox', loadComponent: () => import('./pages/email-inbox/email-inbox.component').then((m) => m.EmailInboxPageComponent) },
  { path: 'admin/email-read', loadComponent: () => import('./pages/email-read/email-read.component').then((m) => m.EmailReadPageComponent) },
  { path: 'admin/email-template', loadComponent: () => import('./pages/email-template/email-template.component').then((m) => m.EmailTemplatePageComponent) },
  { path: 'admin/event-management', loadComponent: () => import('./pages/event-management/event-management.component').then((m) => m.EventManagementPageComponent) },
  { path: 'admin/fees-collection', loadComponent: () => import('./pages/fees-collection/fees-collection.component').then((m) => m.FeesCollectionPageComponent) },
  { path: 'admin/fees-receipt', loadComponent: () => import('./pages/fees-receipt/fees-receipt.component').then((m) => m.FeesReceiptPageComponent) },
  { path: 'admin/form-ckeditor', loadComponent: () => import('./pages/form-ckeditor/form-ckeditor.component').then((m) => m.FormCkeditorPageComponent) },
  { path: 'admin/form-element', loadComponent: () => import('./pages/form-element/form-element.component').then((m) => m.FormElementPageComponent) },
  { path: 'admin/form-pickers', loadComponent: () => import('./pages/form-pickers/form-pickers.component').then((m) => m.FormPickersPageComponent) },
  { path: 'admin/form-validation', loadComponent: () => import('./pages/form-validation/form-validation.component').then((m) => m.FormValidationPageComponent) },
  { path: 'admin/form-wizard', loadComponent: () => import('./pages/form-wizard/form-wizard.component').then((m) => m.FormWizardPageComponent) },
  { path: 'admin/holiday-calendar', loadComponent: () => import('./pages/holiday-calendar/holiday-calendar.component').then((m) => m.HolidayCalendarPageComponent) },
  { path: 'admin/index', loadComponent: () => import('./pages/index/index.component').then((m) => m.IndexPageComponent) },
  { path: 'admin/index-2', loadComponent: () => import('./pages/index-2/index-2.component').then((m) => m.Index2PageComponent) },
  { path: 'admin/index-3', loadComponent: () => import('./pages/index-3/index-3.component').then((m) => m.Index3PageComponent) },
  { path: 'admin/map-jqvmap', loadComponent: () => import('./pages/map-jqvmap/map-jqvmap.component').then((m) => m.MapJqvmapPageComponent) },
  { path: 'admin/menu', loadComponent: () => import('./pages/menu/menu.component').then((m) => m.MenuPageComponent) },
  { path: 'admin/page-error-400', loadComponent: () => import('./pages/page-error-400/page-error-400.component').then((m) => m.PageError400PageComponent) },
  { path: 'admin/page-error-403', loadComponent: () => import('./pages/page-error-403/page-error-403.component').then((m) => m.PageError403PageComponent) },
  { path: 'admin/page-error-404', loadComponent: () => import('./pages/page-error-404/page-error-404.component').then((m) => m.PageError404PageComponent) },
  { path: 'admin/page-error-500', loadComponent: () => import('./pages/page-error-500/page-error-500.component').then((m) => m.PageError500PageComponent) },
  { path: 'admin/page-error-503', loadComponent: () => import('./pages/page-error-503/page-error-503.component').then((m) => m.PageError503PageComponent) },
  { path: 'admin/page-forgot-password', loadComponent: () => import('./pages/page-forgot-password/page-forgot-password.component').then((m) => m.PageForgotPasswordPageComponent) },
  { path: 'admin/page-lock-screen', loadComponent: () => import('./pages/page-lock-screen/page-lock-screen.component').then((m) => m.PageLockScreenPageComponent) },
  { path: 'admin/page-login', loadComponent: () => import('./pages/page-login/page-login.component').then((m) => m.PageLoginPageComponent) },
  { path: 'admin/page-register', loadComponent: () => import('./pages/page-register/page-register.component').then((m) => m.PageRegisterPageComponent) },
  { path: 'admin/post-details', loadComponent: () => import('./pages/post-details/post-details.component').then((m) => m.PostDetailsPageComponent) },
  { path: 'admin/professor-profile', loadComponent: () => import('./pages/professor-profile/professor-profile.component').then((m) => m.ProfessorProfilePageComponent) },
  { path: 'admin/staff-profile', loadComponent: () => import('./pages/staff-profile/staff-profile.component').then((m) => m.StaffProfilePageComponent) },
  { path: 'admin/table-bootstrap-basic', loadComponent: () => import('./pages/table-bootstrap-basic/table-bootstrap-basic.component').then((m) => m.TableBootstrapBasicPageComponent) },
  { path: 'admin/table-datatable-basic', loadComponent: () => import('./pages/table-datatable-basic/table-datatable-basic.component').then((m) => m.TableDatatableBasicPageComponent) },
  { path: 'admin/uc-lightgallery', loadComponent: () => import('./pages/uc-lightgallery/uc-lightgallery.component').then((m) => m.UcLightgalleryPageComponent) },
  { path: 'admin/uc-nestable', loadComponent: () => import('./pages/uc-nestable/uc-nestable.component').then((m) => m.UcNestablePageComponent) },
  { path: 'admin/uc-noui-slider', loadComponent: () => import('./pages/uc-noui-slider/uc-noui-slider.component').then((m) => m.UcNouiSliderPageComponent) },
  { path: 'admin/uc-select2', loadComponent: () => import('./pages/uc-select2/uc-select2.component').then((m) => m.UcSelect2PageComponent) },
  { path: 'admin/uc-sweetalert', loadComponent: () => import('./pages/uc-sweetalert/uc-sweetalert.component').then((m) => m.UcSweetalertPageComponent) },
  { path: 'admin/uc-toastr', loadComponent: () => import('./pages/uc-toastr/uc-toastr.component').then((m) => m.UcToastrPageComponent) },
  { path: 'admin/ui-accordion', loadComponent: () => import('./pages/ui-accordion/ui-accordion.component').then((m) => m.UiAccordionPageComponent) },
  { path: 'admin/ui-alert', loadComponent: () => import('./pages/ui-alert/ui-alert.component').then((m) => m.UiAlertPageComponent) },
  { path: 'admin/ui-badge', loadComponent: () => import('./pages/ui-badge/ui-badge.component').then((m) => m.UiBadgePageComponent) },
  { path: 'admin/ui-button', loadComponent: () => import('./pages/ui-button/ui-button.component').then((m) => m.UiButtonPageComponent) },
  { path: 'admin/ui-button-group', loadComponent: () => import('./pages/ui-button-group/ui-button-group.component').then((m) => m.UiButtonGroupPageComponent) },
  { path: 'admin/ui-card', loadComponent: () => import('./pages/ui-card/ui-card.component').then((m) => m.UiCardPageComponent) },
  { path: 'admin/ui-carousel', loadComponent: () => import('./pages/ui-carousel/ui-carousel.component').then((m) => m.UiCarouselPageComponent) },
  { path: 'admin/ui-dropdown', loadComponent: () => import('./pages/ui-dropdown/ui-dropdown.component').then((m) => m.UiDropdownPageComponent) },
  { path: 'admin/ui-grid', loadComponent: () => import('./pages/ui-grid/ui-grid.component').then((m) => m.UiGridPageComponent) },
  { path: 'admin/ui-list-group', loadComponent: () => import('./pages/ui-list-group/ui-list-group.component').then((m) => m.UiListGroupPageComponent) },
  { path: 'admin/ui-media-object', loadComponent: () => import('./pages/ui-media-object/ui-media-object.component').then((m) => m.UiMediaObjectPageComponent) },
  { path: 'admin/ui-modal', loadComponent: () => import('./pages/ui-modal/ui-modal.component').then((m) => m.UiModalPageComponent) },
  { path: 'admin/ui-pagination', loadComponent: () => import('./pages/ui-pagination/ui-pagination.component').then((m) => m.UiPaginationPageComponent) },
  { path: 'admin/ui-popover', loadComponent: () => import('./pages/ui-popover/ui-popover.component').then((m) => m.UiPopoverPageComponent) },
  { path: 'admin/ui-progressbar', loadComponent: () => import('./pages/ui-progressbar/ui-progressbar.component').then((m) => m.UiProgressbarPageComponent) },
  { path: 'admin/ui-tab', loadComponent: () => import('./pages/ui-tab/ui-tab.component').then((m) => m.UiTabPageComponent) },
  { path: 'admin/ui-typography', loadComponent: () => import('./pages/ui-typography/ui-typography.component').then((m) => m.UiTypographyPageComponent) },
  { path: 'admin/widget-basic', loadComponent: () => import('./pages/widget-basic/widget-basic.component').then((m) => m.WidgetBasicPageComponent) },
  { path: 'index', pathMatch: 'full', redirectTo: 'courses' },
  { path: 'about-courses', pathMatch: 'full', redirectTo: 'admin/about-courses' },
  { path: 'about-student', pathMatch: 'full', redirectTo: 'admin/about-student' },
  { path: 'add-blog', pathMatch: 'full', redirectTo: 'admin/add-blog' },
  { path: 'add-courses', pathMatch: 'full', redirectTo: 'admin/add-courses' },
  { path: 'add-departments', pathMatch: 'full', redirectTo: 'admin/add-departments' },
  { path: 'add-email', pathMatch: 'full', redirectTo: 'admin/add-email' },
  { path: 'add-fees', pathMatch: 'full', redirectTo: 'admin/add-fees' },
  { path: 'add-holiday', pathMatch: 'full', redirectTo: 'admin/add-holiday' },
  { path: 'add-library', pathMatch: 'full', redirectTo: 'admin/add-library' },
  { path: 'add-professor', pathMatch: 'full', redirectTo: 'admin/add-professor' },
  { path: 'add-staff', pathMatch: 'full', redirectTo: 'admin/add-staff' },
  { path: 'add-student', pathMatch: 'full', redirectTo: 'admin/add-student' },
  { path: 'all-courses', pathMatch: 'full', redirectTo: 'admin/all-courses' },
  { path: 'all-departments', pathMatch: 'full', redirectTo: 'admin/all-departments' },
  { path: 'all-holiday', pathMatch: 'full', redirectTo: 'admin/all-holiday' },
  { path: 'all-library', pathMatch: 'full', redirectTo: 'admin/all-library' },
  { path: 'all-professors', pathMatch: 'full', redirectTo: 'admin/all-professors' },
  { path: 'all-staff', pathMatch: 'full', redirectTo: 'admin/all-staff' },
  { path: 'all-students', pathMatch: 'full', redirectTo: 'admin/all-students' },
  { path: 'app-calender', pathMatch: 'full', redirectTo: 'admin/app-calender' },
  { path: 'app-profile', pathMatch: 'full', redirectTo: 'admin/app-profile' },
  { path: 'blog', pathMatch: 'full', redirectTo: 'admin/blog' },
  { path: 'blog-category', pathMatch: 'full', redirectTo: 'admin/blog-category' },
  { path: 'chart-chartist', pathMatch: 'full', redirectTo: 'admin/chart-chartist' },
  { path: 'chart-chartjs', pathMatch: 'full', redirectTo: 'admin/chart-chartjs' },
  { path: 'chart-flot', pathMatch: 'full', redirectTo: 'admin/chart-flot' },
  { path: 'chart-morris', pathMatch: 'full', redirectTo: 'admin/chart-morris' },
  { path: 'chart-peity', pathMatch: 'full', redirectTo: 'admin/chart-peity' },
  { path: 'chart-sparkline', pathMatch: 'full', redirectTo: 'admin/chart-sparkline' },
  { path: 'content', pathMatch: 'full', redirectTo: 'admin/content' },
  { path: 'content-add', pathMatch: 'full', redirectTo: 'admin/content-add' },
  { path: 'ecom-checkout', pathMatch: 'full', redirectTo: 'admin/ecom-checkout' },
  { path: 'ecom-customers', pathMatch: 'full', redirectTo: 'admin/ecom-customers' },
  { path: 'ecom-invoice', pathMatch: 'full', redirectTo: 'admin/ecom-invoice' },
  { path: 'ecom-product-detail', pathMatch: 'full', redirectTo: 'admin/ecom-product-detail' },
  { path: 'ecom-product-grid', pathMatch: 'full', redirectTo: 'admin/ecom-product-grid' },
  { path: 'ecom-product-list', pathMatch: 'full', redirectTo: 'admin/ecom-product-list' },
  { path: 'ecom-product-order', pathMatch: 'full', redirectTo: 'admin/ecom-product-order' },
  { path: 'edit-courses', pathMatch: 'full', redirectTo: 'admin/edit-courses' },
  { path: 'edit-departments', pathMatch: 'full', redirectTo: 'admin/edit-departments' },
  { path: 'edit-holiday', pathMatch: 'full', redirectTo: 'admin/edit-holiday' },
  { path: 'edit-library', pathMatch: 'full', redirectTo: 'admin/edit-library' },
  { path: 'edit-professor', pathMatch: 'full', redirectTo: 'admin/edit-professor' },
  { path: 'edit-profile', pathMatch: 'full', redirectTo: 'admin/edit-profile' },
  { path: 'edit-staff', pathMatch: 'full', redirectTo: 'admin/edit-staff' },
  { path: 'edit-student', pathMatch: 'full', redirectTo: 'admin/edit-student' },
  { path: 'email-compose', pathMatch: 'full', redirectTo: 'admin/email-compose' },
  { path: 'email-inbox', pathMatch: 'full', redirectTo: 'admin/email-inbox' },
  { path: 'email-read', pathMatch: 'full', redirectTo: 'admin/email-read' },
  { path: 'email-template', pathMatch: 'full', redirectTo: 'admin/email-template' },
  { path: 'event-management', pathMatch: 'full', redirectTo: 'admin/event-management' },
  { path: 'fees-collection', pathMatch: 'full', redirectTo: 'admin/fees-collection' },
  { path: 'fees-receipt', pathMatch: 'full', redirectTo: 'admin/fees-receipt' },
  { path: 'form-ckeditor', pathMatch: 'full', redirectTo: 'admin/form-ckeditor' },
  { path: 'form-element', pathMatch: 'full', redirectTo: 'admin/form-element' },
  { path: 'form-pickers', pathMatch: 'full', redirectTo: 'admin/form-pickers' },
  { path: 'form-validation', pathMatch: 'full', redirectTo: 'admin/form-validation' },
  { path: 'form-wizard', pathMatch: 'full', redirectTo: 'admin/form-wizard' },
  { path: 'holiday-calendar', pathMatch: 'full', redirectTo: 'admin/holiday-calendar' },
  { path: 'index-2', pathMatch: 'full', redirectTo: 'admin/index-2' },
  { path: 'index-3', pathMatch: 'full', redirectTo: 'admin/index-3' },
  { path: 'map-jqvmap', pathMatch: 'full', redirectTo: 'admin/map-jqvmap' },
  { path: 'menu', pathMatch: 'full', redirectTo: 'admin/menu' },
  { path: 'page-error-400', pathMatch: 'full', redirectTo: 'admin/page-error-400' },
  { path: 'page-error-403', pathMatch: 'full', redirectTo: 'admin/page-error-403' },
  { path: 'page-error-404', pathMatch: 'full', redirectTo: 'admin/page-error-404' },
  { path: 'page-error-500', pathMatch: 'full', redirectTo: 'admin/page-error-500' },
  { path: 'page-error-503', pathMatch: 'full', redirectTo: 'admin/page-error-503' },
  { path: 'page-forgot-password', pathMatch: 'full', redirectTo: 'admin/page-forgot-password' },
  { path: 'page-lock-screen', pathMatch: 'full', redirectTo: 'admin/page-lock-screen' },
  { path: 'page-login', pathMatch: 'full', redirectTo: 'admin/page-login' },
  { path: 'page-register', pathMatch: 'full', redirectTo: 'admin/page-register' },
  { path: 'post-details', pathMatch: 'full', redirectTo: 'admin/post-details' },
  { path: 'professor-profile', pathMatch: 'full', redirectTo: 'admin/professor-profile' },
  { path: 'staff-profile', pathMatch: 'full', redirectTo: 'admin/staff-profile' },
  { path: 'table-bootstrap-basic', pathMatch: 'full', redirectTo: 'admin/table-bootstrap-basic' },
  { path: 'table-datatable-basic', pathMatch: 'full', redirectTo: 'admin/table-datatable-basic' },
  { path: 'uc-lightgallery', pathMatch: 'full', redirectTo: 'admin/uc-lightgallery' },
  { path: 'uc-nestable', pathMatch: 'full', redirectTo: 'admin/uc-nestable' },
  { path: 'uc-noui-slider', pathMatch: 'full', redirectTo: 'admin/uc-noui-slider' },
  { path: 'uc-select2', pathMatch: 'full', redirectTo: 'admin/uc-select2' },
  { path: 'uc-sweetalert', pathMatch: 'full', redirectTo: 'admin/uc-sweetalert' },
  { path: 'uc-toastr', pathMatch: 'full', redirectTo: 'admin/uc-toastr' },
  { path: 'ui-accordion', pathMatch: 'full', redirectTo: 'admin/ui-accordion' },
  { path: 'ui-alert', pathMatch: 'full', redirectTo: 'admin/ui-alert' },
  { path: 'ui-badge', pathMatch: 'full', redirectTo: 'admin/ui-badge' },
  { path: 'ui-button', pathMatch: 'full', redirectTo: 'admin/ui-button' },
  { path: 'ui-button-group', pathMatch: 'full', redirectTo: 'admin/ui-button-group' },
  { path: 'ui-card', pathMatch: 'full', redirectTo: 'admin/ui-card' },
  { path: 'ui-carousel', pathMatch: 'full', redirectTo: 'admin/ui-carousel' },
  { path: 'ui-dropdown', pathMatch: 'full', redirectTo: 'admin/ui-dropdown' },
  { path: 'ui-grid', pathMatch: 'full', redirectTo: 'admin/ui-grid' },
  { path: 'ui-list-group', pathMatch: 'full', redirectTo: 'admin/ui-list-group' },
  { path: 'ui-media-object', pathMatch: 'full', redirectTo: 'admin/ui-media-object' },
  { path: 'ui-modal', pathMatch: 'full', redirectTo: 'admin/ui-modal' },
  { path: 'ui-pagination', pathMatch: 'full', redirectTo: 'admin/ui-pagination' },
  { path: 'ui-popover', pathMatch: 'full', redirectTo: 'admin/ui-popover' },
  { path: 'ui-progressbar', pathMatch: 'full', redirectTo: 'admin/ui-progressbar' },
  { path: 'ui-tab', pathMatch: 'full', redirectTo: 'admin/ui-tab' },
  { path: 'ui-typography', pathMatch: 'full', redirectTo: 'admin/ui-typography' },
  { path: 'widget-basic', pathMatch: 'full', redirectTo: 'admin/widget-basic' },
  { path: '**', redirectTo: 'courses' }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}
