# ======= Configuration de BASE =======
spring.application.name=evenementiel-ms
server.port=8083

# ======= Etape 1: Eureka & Config Server =======
# Connexion à Eureka Server pour que la Gateway nous trouve
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Spring Cloud Config Server (Import Optionnel pour ne pas planter s'il n'est pas allumé)
spring.config.import=optional:configserver:http://localhost:8888

# ======= Etape 3: RabbitMQ (Communication Asynchrone) =======
# Connexion au serveur RabbitMQ local (par défaut sur 5672)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ======= Etape 4: Keycloak (Securisation Oauth2) =======
# Valider les tokens (JWT) générés par le serveur Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/e-learn-realm

# ======= Base de Données H2 (En mémoire) =======
spring.datasource.url=jdbc:h2:mem:elearn_evenement
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Activation de la console H2 pour le debug
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Demande à Hibernate de créer/mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
