# Port du serveur de configuration
server.port=8888

# Nom du microservice
spring.application.name=config-server

# Activer le lecteur basé sur le système de fichiers (natif)
spring.profiles.active=native

# Le dossier où seront stockés les fichiers de configuration de tous les microservices
spring.cloud.config.server.native.search-locations=classpath:/config

# Enregistrement auprès d'Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
