spring.application.name=cours
server.port=8082
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

# Activer console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Config DB
spring.datasource.url=jdbc:h2:mem:coursdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


file.upload.images=uploads/images/
file.upload.videos=uploads/videos/

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Groq API Key
groq.api.key=YOUR_GROQ_API_KEY_HERE
