# ======= Configuration de BASE =======
spring.application.name=evenementiel-ms
server.port=8083

# ======= Etape 1: Eureka & Config Server =======
# Connexion à Eureka Server pour que la Gateway nous trouve
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Spring Cloud Config Server (Import Optionnel pour ne pas planter s'il n'est pas allumé)
spring.config.import=optional:configserver:http://localhost:8888

# ======= Etape 3: RabbitMQ (Communication Asynchrone) =======
# Connexion au serveur RabbitMQ local (par défaut sur 5672)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ======= Etape 4: Keycloak (Securisation Oauth2) =======
# Valider les tokens (JWT) générés par le serveur Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/e-learn-realm

# ======= Base de Données XAMPP (MySQL) =======
spring.datasource.url=jdbc:mysql://localhost:3306/elearn_evenement?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Demande à Hibernate de créer/mettre à jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
